name: CodeNarc Tests
on: [push]
jobs:
  gradle_test:
    name: Run CodeNarc linter
    runs-on: ubuntu-latest
    container: codenarc/codenarc:latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Gradle tests
      run: >-
        java -jar /lib/codenarc-all.jar
          -includes='**/*Jenkinsfile,**/*.groovy'

